name: workspace
services:
  identity_database:
    image: postgres:17.2
    environment:
      POSTGRES_DB: ${IDENTITY_DATABASE}
      POSTGRES_PASSWORD: ${IDENTITY_DATABASE_PASSWORD}
      POSTGRES_USER: ${IDENTITY_DATABASE_USER}
      PGTZ: UTC
      TZ: UTC
    ports:
      - '127.0.0.1:${IDENTITY_DATABASE_PORT}:5432'
    restart: unless-stopped
    volumes:
      - ./apis/identity/database/volume:/var/lib/postgresql/data
